### ISSUE TITLE
Support for other database types

### ISSUE THREAD

**Issue by timwis** [web-pal/DBGlass#10]
Hey, really awesome job on this project! A few months ago I started working on the same idea with [dataface](https://github.com/timwis/dataface). I didn't get as far as you did, and frankly I'm glad this came out so that I don't need to! One feature I was excited about, though, was support for multiple database types, primarily leveraging [knex.js](http://knexjs.org/) for query building. Knex doesn't quite do _everything_, but my plan was to use basic class inheritance to write DB-specific queries for things that knex didn't support. [Here's what I mean](https://github.com/timwis/dataface/tree/master/public/src/clients).

Any thoughts about supporting more database types?

**Comment by ilya-lopukhin** [comment]
We are planning to include MySQL and MariaDB support in future. Thanks for your advice on [knex.js](http://knexjs.org/)

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
