### ISSUE TITLE
Ability to run custom queries

### ISSUE THREAD

**Issue by pkkid** [web-pal/DBGlass#16]
Having the ability to build an run my own custom SQL query (with the option to cancel long running requests) would make this tool a powerful replacement to the current tools I use.

**Comment by VladimirPal** [comment]
@mjs7231 It's a very good idea, we'll implement it soon. Thank you.

**Comment by thib-rdr** [comment]
I second that, being able to run custom queries is an absolute requirement for it to become an everyday tool. Also, a history of the queries I ran would be icing on the top 👍

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
