### ISSUE TITLE
'Private key' button does not respond

### ISSUE THREAD

**Issue by thib-rdr** [web-pal/DBGlass#18]
Trying to add a new connection, connecting via SSH, filled all the fields, but the button 'Private key' doesn't do anything. Is this an already known bug ?

I'm on Mac OS X El Capitan.

**Comment by VladimirPal** [comment]
@GaryHost No, This should work. Can you give us more details? What operating system?

**Comment by thib-rdr** [comment]
Yeah sorry, i'm on Mac OS X El Capitan 10.11.13, and i've downloaded the v0.1.0-beta.1 version.

**Comment by VladimirPal** [comment]
@GaryHost Thank you very much that found it. Fixed in [v0.1.0-beta.2](https://github.com/web-pal/DBGlass/releases)
