### ISSUE TITLE
The server does not support SSL connections

### ISSUE THREAD

**Issue by taniadaniela** [web-pal/DBGlass#25]
I'm having this issue even when connect via ssh is off. 
Version 0.1.0-beta.3 (0.1.0-beta.3)

**Comment by VladimirPal** [comment]
@taniadaniela Thank you for the issue, i've fixed it on a new version(0.1.0-beta.4), try it please.

**Comment by raxkin** [comment]
It works now!

**Comment by taniadaniela** [comment]
totally working, thanks for the fast fix!
