### ISSUE TITLE
Update with character "[" 

### ISSUE THREAD

**Issue by raxkin** [web-pal/DBGlass#26]
I can't update a row when there is a column that contains the character "[".
This only happen when you have a table with **no primary key**
Table exemple:
![screenshot from 2016-10-21 10-27-02](https://cloud.githubusercontent.com/assets/6256714/19591884/83116da0-9779-11e6-9085-83d3e8e089df.png)

And this is the result when i try to change any column: 
![screenshot from 2016-10-21 10-34-03](https://cloud.githubusercontent.com/assets/6256714/19592029/4ea56dc2-977a-11e6-9834-ebd0f68e9d74.png)

As I can see, if you create a new table and add a column with that character and then updates another column it works, but if you change the table and return to the table, when you try to update the column it will give you the error.

This also happens when you put  the character in any position of the text

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
