### ISSUE TITLE
cmd+s to confirm save

### ISSUE THREAD

**Issue by joseramonc** [web-pal/DBGlass#27]
In the same way `Undo` works with `cmd+u` when I'm done making changes it would be nice to be able to confirm my changes pressing `cmd+s` as the shortcut for clicking `save` button:
![screen shot 2016-10-21 at 10 00 57 am](https://cloud.githubusercontent.com/assets/1993929/19603057/4e14bc1e-9775-11e6-889c-1b507f565ac9.png)

**Comment by VladimirPal** [comment]
@joseramonc It's a very good idea. Thank you.

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
