### ISSUE TITLE
Drop/truncate table not working

### ISSUE THREAD

**Issue by nfons** [web-pal/DBGlass#30]
Open connection,

on tables view, right click and "drop table" or truncate table

observe popup, that asks if you are sure. click to positive button.

a new pop up for delete/clone row shows up (this is the same as if you alt click on a record)

I think the alt click is sticking, and when you click the confirmation popup, it is assuming you are clicking on a record.

**Comment by jpAgendize** [comment]
Same issue here!

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
