### ISSUE TITLE
Change database on same connection

### ISSUE THREAD

**Issue by joseramonc** [web-pal/DBGlass#32]
The idea is to choose from your list of databases in the current connection (similar to current connection click dropdown with favorites appear)

Quick (and ugly) preview of what I'm saying:
![screen shot 2016-11-30 at 11 35 28 am](https://cloud.githubusercontent.com/assets/1993929/20763781/1ff92c20-b6f1-11e6-8625-d9a51f6f2ac5.png)

It don't have to be like that but that's the feature I'd like.

Thanks

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
