### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by agustif** [web-pal/DBGlass#34]
Would it be something that could make it to master a PR to add a dark theming option?

**Comment by ilya-lopukhin** [comment]
Can't really understand what you mean, but as far as i did, you want to add some new theming functionality. If so, it would be great! We highly appreciate any PRs to make dbglass better (as for now we don't have much time to do it ourselves), feel free to participate!

**Comment by agustif** [comment]
Yep, I would like to add an option to have a full-dark theme instead of dark-white mix, I just spend too much hours during the night refreshing and staring to my instance of postgresql thanks to DBGlass.

**Comment by ilya-lopukhin** [comment]
Great. The code is quite a mess right now, so if you have any questions, don't hestitate to write me a letter or two. I would explain details, or help as i can.

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
