### ISSUE TITLE
escaping String based IDs

### ISSUE THREAD

**Issue by zthomas** [web-pal/DBGlass#36]
If the id of a row is a string, like UUID, then the query that's generated is not valid. It needs quotations around the id.

**Comment by G3z** [comment]
I noticed it escapes the column if the uuid is a primary key while it fails if it isn't ( like in many_to_many relation tables)

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46

**Comment by timwis** [comment]
Does closing this issue and writing `#46` mean that you've resolved this issue? Or that you'd rather people just wait for the new version to be released than keep issues open?

**Comment by VladimirPal** [comment]
@timwis Unfortunately we have very few resources and we can't support previous version, in the end it was just beta and we have drawn conclusions for new version.
