### ISSUE TITLE
Date field data represented by {} (Postgres)

### ISSUE THREAD

**Issue by jarnell** [web-pal/DBGlass#45]
I haven't tried other databases, but when using Postgres, data in a field of type 'date' isn't displayed. Instead it is represented by '{}'.
![dbglass](https://cloud.githubusercontent.com/assets/1726633/24321581/eb774374-114f-11e7-8d2b-3d5b2d81b7d2.jpg)

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
