### ISSUE TITLE
Support postgres scheme?

### ISSUE THREAD

**Issue by sedrakpc** [web-pal/DBGlass#5]
Looks like application supports only public scheme right now.

**Comment by VladimirPal** [comment]
@sedrakpc Can you clarify please what's you mean

**Comment by sedrakpc** [comment]
Here is a screenshot of my database from pgadmin:
<img width="327" alt="screen shot 2016-10-10 at 7 21 39 pm" src="https://cloud.githubusercontent.com/assets/6464002/19243117/ec2e40f0-8f1e-11e6-9717-e65ac790b44f.png">

This one from DBGlass:
<img width="214" alt="screen shot 2016-10-10 at 7 22 20 pm" src="https://cloud.githubusercontent.com/assets/6464002/19243157/17e96ff8-8f1f-11e6-9b95-8a9698683076.png">

Seems application only shows tables from public scheme.

**Comment by VladimirPal** [comment]
@sedrakpc Thank you, we'll fix it

**Comment by jmealo** [comment]
Looks great so far. Properly supporting schemas and search path are a must. :+1:

**Comment by cbertelli** [comment]
Yes, definitely worth the effort. Thanks

**Comment by VladimirPal** [comment]
https://github.com/web-pal/DBGlass/issues/46
