### ISSUE TITLE
Doesn't work with no password user

### ISSUE THREAD

**Issue by fzaninotto** [web-pal/DBGlass#6]
Password is compulsory in the login screen, but my (localhost) user has none. I know it's bad, except it's the default with Postres.app - I'm probably not the only one with the issue.

**Comment by VladimirPal** [comment]
@fzaninotto Thank you, we'll fix it soon.

**Comment by fzaninotto** [comment]
Seems to me that https://github.com/web-pal/DBGlass/blob/master/app/components/Connect/Content/validateForm.js#L24 is a good starting point.
